openapi: 3.0.3
info:
  title: SmartCampus-Problem Domain
  description: SmartCampus-Problem Domain specified as REST-API
  version: 1.2.1

paths:

  /problems:
    get:
      summary: List all problems
      description: Lists all problems which are embedded in the domain database.
      tags:
        - Problems
      responses:
        200:
          $ref: '#/components/responses/problem'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.
    post:
      summary: Create a problem
      description: Creates a new problem and adds it to the domain database.
      tags:
        - Problems
      requestBody:
        $ref: '#/components/requestBodies/problem'
      responses:
        200:
          $ref: '#/components/responses/problem'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.
    put:
      summary: Update a problem
      description: Update a specific building from the domain database.
      tags:
        - Problems
      requestBody:
        $ref: '#/components/requestBodies/problem'
      responses:
        200:
          $ref: '#/components/responses/problem'
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

  /problems/{pin}:
    parameters:
      - $ref: '#/components/parameters/pin'
    get:
      summary: Get a problem
      description: Get a specific problem from the domain database.
      tags:
        - Problems
      responses:
        200:
          $ref: '#/components/responses/problem'
        400:
          description: invalid request message framing.
        404:
          description: Requested data doesn't exist.
    delete:
      summary: Remove a problem
      description: Remove a specific problem from the domain database.
      tags:
        - Problems
      responses:
        200:
          description: Succesfully deleted.
        400:
          description: invalid request message framing.
        401:
          description: unauthorized access.
        404:
          description: Requested data doesn't exist.

components:

  requestBodies:
    problem:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/problem'

  responses:
    problem:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/problem'

  parameters:

    pin:
      in: path
      name: pin
      required: true
      description: The Problem Identification Number (PIN) as unique number of a problem.
      style: simple
      schema:
        $ref: '#/components/schemas/pin'

  schemas:

    # single value schemas

    pin:
      type: string
      example: p-371
      minimum: 1

    # multi value schemas

    problem:
      type: object
      properties:
        reference_identification_number:
          type: string
          example: "b-234"
        identification_number:
          type: string
          example: "p-2312"
        notification_identification_number:
          type: string
          example: "n-232"
        problem_state:
          $ref: '#/components/schemas/problem_state'
        problem_title:
          type: string
          example: "Elevator is stuck"
        problem_description:
          type: string
          example: "in 2. floor"
        creation_date:
          type: string
          format: date
        problem_reporter:
          type: string
          example: "uxxxx@student.kit.edu"

    problem_state:
      type: string
      enum:
        - accepted
        - declined
        - in_progress
        - open
        - closed
